//
//  ViewController.swift
//  GC Licensing Exam
//
//  Created by MacBook Pro on 1/19/21.
//

import UIKit

class ViewController: UIViewController {
    @IBOutlet var questionLabel: UILabel!
    @IBOutlet var answerLabel: UILabel!
    
    let questions: [String] = [
        "1. Detached one- and two-familiy dwellings must comply with: ",
        "2. The purpose of the IBC code is to make sure the minimum requirements to protect public health, safety and general _______ are met",
        "3. The ICC Electrical Code applies to the installation of: ",
        "4. Installation and repair of a water or sewage system must be done in compliance with this code: ",
        "5. International Property Maintenance Code applies to:",
        "6. The building official has authority too",
        "7. Owners can obtain building permits after taking which step?",
        "8. Permits are not required for:",
        "9. Emergency repairs must be reported within?",
        "10. Applications are required for: ",
        "11. Permits are not required for?",
        "12. Applications for permits are abandoned after:",
        "13. Building permit or copy must be kept where?",
        "14. Construction documents must be prepared by",
        "15. The construction documents must show, in detail, the location, construction, size, and characteristics of: ",
        "16. An approved construction document must have writing or a stamp that states: ",
        "17. _____ are defined as portions of the design that are not submitted at the time of the application. ",
        "18. Any changes made during construction that are not in compliance with the approved construction documents must be submitted as: ",
        "19. Construction work that requires inspection must be ______ and exposed for inspection purposes. ",
        "20. A certificate of occupancy must include the following: ",
        "21. The building official is authorized to issue a temporary certificate of ____ before the completion of work",
        "22. If anyone disagrees with a decision by building official, you must file with the: ",
        "23. Reports of inspection must be made in writing and ______",
        "24. Reports from any required testing must be kept by: ",
        "25. Any person who is granted annual permit must keep a detailed record of: ",
        "BEGIN TRUE/FALSE FOR ADMISTRATION QUESTIONS",
        "1. The provisions of the IBC code apply to painting, papering, tiling, or other similiar finish work",
        "2. The provisions of the International Private Sewage Disposal Code must be applied to the installation of plumbing systems.",
        "3. The building official is not liable for cost in any suit that occurs.",
        "4. Used equipment can be resued without approval from the building official",
        "5. The building official has the authority to grant modifications at his or her descretions",
        "6. Permits are not required for the construction of oil derricks.",
        "7. Replacement or relocation of standpipe is considered to be a repiar, and no permit is needed. ",
        "8. The building official has the right to reject any permit application that does not conform the code",
        "9. Construction decuments must be dimensioned and drawn on correct material.",
        "10. The only time you need a site plan is for the construction",
        "11. When approved, construction documents must always",
        "12. Electronic-media documents are allowed when approved by the building official",
        "13. Your permit will not be valid until all fees have been paid by the building official",
        "14. A one-time fee is charged for all permits that you need.",
        "15. The building official is authorized to create a refund policy",
        "16. The building official can make inspections wihtout notice",
        "17. Footing and foudation inspections must be approved before excavations are made",
        "18. Protection of joints and penetrations in fire-resistence-rated assemblies must be concealed from view until inspected and approved",
        "19. The building official will accept reports of approved inpsection agencies if the agencies meet the requirements",
        "20. The building inspector will call the owner to make an appointment for building inspection.",
        "21. A building owner can hook up fuel and power without a permit",
        "22. A stop-work order is just a threat that the building official uses; it is never enforeced",
        "23. The board of appeals cannot waive any requirements of the IBC code.",
        "24. A permit valuation includes everything but labor",
        "25. An application for a permit must include the value of the work to be done",
        "Chapter 2: Definitions",
        "1. What doe the letters in AAC masonary stand for?",
        "2. A continous, unobstructed path is the defintion for which of the following words?",
        "3. ________ Is finely divided solid material that, when dispersed in the air in the proper proportions, could be ignited by flame or spark",
        "4. Combustabile liquid is defined as having a closed cup point at or above one of the following temperatures in degrees Farenheit:",
        "5. Which of the following is capable of being readily ignited from common sources of heat or at a temperature of 600 degrees Fahrenheit",
        " 6. Hazardous materials are chemicals or substances that are physical or health hazards and are defined and classified by which of these codes?",
        " 7. Materials that when mixed have the potential to react in a manner that generates heat, fumes, or gases that are hazardous to life or property are defined as one of the following: ",
        " 8. A device that is designed to discover the presence of fire and initiate action is defined as: ",
        "9. Bleachers are defined as one of the following: ",
        "10. The leading edge of treads of stairs and of landings at the top of a stairway flights is defined as one of these: ",
        "11. Veners that are secured with approved mechanical fasteners are called: ",
        "12. An interlayment is a layer of felt or nonbituminous saturated felt that is no less than ______ inches wide.",
        "13. Reroofing is also known as: ",
        "14. A scupper is what? ",
        "15. An approved fabricator is defined as: ",
        "16. A metal rod, wire, or strap that secures masonary to its structural support is called: ",
        "17. This type of dimension is defined as having a specified dimension plus an allowance for the joints with the units are to be laid.",
        "18. The commerical size in standard sawn and glued-laminated lumber grade is: ",
        "19. Particle board is a generic term for a panel primarly composed of _____ materials (usually wood) in the form of pieces or particles",
        "20. The following woods are defined as termite-resistant: ",
        "21. The grade of lumber is defined as: ",
        "22. Black locust is which type of wood: ",
        "23. ANSI denotes which organization: ",
        "24. Which of the following describes a townhouse?",
        "25. Liquids that have a closed cup flash point at or above 200 degrees F are classified as: ",
        "Definitions",
        "1. Aerosol products must be specified as Level 1, 2, or 3",
        "2. Cryogenic fluid has a boiling point lower than 150 degrees F at 14.7 pounds per square inch. ",
        "3. A helistop is the same as a heliport, except that no fuel, maintenance, repair, storage is permitted",
        "4. HPM stands for Hazardous Production Material. ",
        "5. A basement must be considered as a story above the grade above the grade plane if the finshed surface is less than 6 feet. ",
        "6. An intermediate level or levels between between the floor and ceiling of any story of any story is the correct defintion of mezzanine, ",
        "7. A fire partition is a horizontal assembly of materials designed to restrict the spread of the fire by protecting openings. ",
        "8. The fire-seperation distance is not to be measured from the building face to the side of the wall. ",
        "9. Construction documents can be written, graphic, or pictorial. ",
        "10. A vertical assembly is a fire-resistence-rated floor or roof assembly of materials designed to restrict the spread of fire.",
        "11. A concrete-fiber blanket is a lightweight insulating material made of alumina-silica and shale. ",
        "12. Interior finish includes interior wall and roof finishes. ",
        "13. The definition of trim includes picture molds, chair rails, baseboards, and protective materials in fixed application. ",
        "14. A speaker or horn is part of an alarm-notification appliance",
        "15. An egress court is a yard or court that provides access to a public way for one or more exits. ",
        "16. Panic hardware that is listed for on fire-door assemblies is called fire-entracne hardware.",
        "17. Nosing is defined as people who snoon around on building and construction sites. ",
        "18. An entrance that is not a service entrance or a restricted entrance is called a public entrance. ",
        "19. A scupper is a type of roof replacement. ",
        "20. A diaphram is the product of a nominal strength and a resistance or strength-reduction factor. ",
        "21. A factored load is defined as the product of nominal load and a load factor  ",
        "22. Load effects are condtions beyond a structure beomces unfit for service and is judged to be no longer useful. ",
        "23. To be in two horizontal directions at 90 degrees to each other is considered to be orthogonal. ",
        "24. Sprayed fire-resistent materials are defined as fibrous materials that are applied by spraying to provide fire-resistent protection. ",
        "25. Timber piles are made up of all the trees that have ben cut from the construction or building site. ",
        "Use and Occupancy Classifications",
        "1. _____ performing arts are classified as Group A-1 assemblies ",
        "2. Buildings such as courtrooms, lecture halls, and mueseums are classified as _____",
        "3. Group B is classified as:_______ ",
        "4. High hazard such as ____________ belong to Group H",
        "5. Group I-1 occupancy includes buildings or structures that house more that __ people. ",
        "6.  ______ and _____ centers are classified as Group I-1 occcpanices. ",
        "7. Group M occupancies may include buildings for the display and sale of _____",
        "8. ___________ is an occupancy of a dwelling or sleeping unit for not more than 30 days. ",
        "9. Leather is considered to belong to __________ hazard storage. ",
        "10. Group U is classifed as ______ and ________",
        "11. Religous educational rooms that have an occupant load of fewer than _____ poeple must be classifed as A-3 occupancies. ",
        "12. Factory industrial uses that are low-hazard must be classifed as ______ occupancies. ",
        "13. High-hazard Group-H must be in accordance with the ___________",
        "14. Buildings that contain materials that are health hazards such as highly _____ materials must be classified as Group H-4. ",
        "15. A building arranged or used for lodging for compensations, with or without meals, and not occupied as a single-family unit is a _____ house",
        "16. A building that houses residents who do not require medical or nursing care is a ______ care service. ",
        "17. _______ living facilities are building or parts of buildings that contain sleeping units for which residents share bathroom and/or kitchen facilities. ",
        "18. Rooms in a building where students ",
        "19. Greenhouses are classified as Group ______",
        "20. Adult and childcare facalities that are within a single-family",
        "21. A buidling used for assembly purposes with an occumpancy load of fewer than ___ persons must be classified as Group B occupancy",
        "22. Assebmly uses intended for food and/or drink consumption include ______",
        "23. Group I-3 occupancy includes buildings that are inhabited by more than five persons who are under constraint such as ____",
        "24. Group ____ includes buildings used for the storage of noncombustible materials such as glass or frozen foods. ",
        "25. Group E is classified as _____ occupancy",
        "True/False for Use and Occupancy Classifications",
        "1. A seperate singe-story building without a basement or crawl space that is used for storage is a detached building.",
        "2. Explosives can include dynamic igniters and fireword",
        "3. Class V formulations burn intensely and pose a hazard.",
        "4. An oxidizer is a material that gives off gas; chlorine is classified as an oxidizer. ",
        "5. A chemical that has a lethal",
        "6. Pyrophoric is a chemical with an auto-ingition temperature in air at or below 110 degrees Fahrenheit. ",
        "7. Organic peroxides decompose into various unstable compounds over a long period of time. ",
        "8. Materials that react explosively with water without heat or confinement are include in Class 3. ",
        "9. A room or space that is used for assembly purposes, is less than 750 square feet in area, and is accesory to another occupnacy must be classified as Group A",
        "10. Amusement parks and post offices are classified in the same group. ",
        "11. Corrosives include personal and household products. ",
        "12. Stationary batteries used for facility emergency power are covered under the International Mechanical Code",
        "13. An aerosol is a product that is dispensed from the aeresol container by a propelent. ",
        "14. Aerosol products do not have a designated level",
        "15. Baled cotton is a natural seed fiber wrapped and secured with industrial-accepted materials",
        "16. Densely packed baled cotton must be 55 inches in length, 21 inches wide, and 27.6 to 35.4 inches high. ",
        "17. An artificial barricade is an artificial mound with a mininum thickness of 3 feet. ",
        "18. Examples of closed systems for solids and liquids include product flow-through distillation.  ",
        "19. Dry boxes are portable magazines designed to hold liquids such as water. ",
        "20. Group U occupancies includes greenhoues and carports.  ",
        "21. Low-hazard products are permitted to be wrapped in plastic. ",
        "22. Buildings in Group I-3 are classified as one of five occupancy conditions.  ",
        "23. Group I, the instutional group, does not include assisted living facilities.  ",
        "24. High-hazard group H-1 is classified in divisions, such as explosives. ",
        "25. Electrical coils are classified as storage, Group S-1. ",
        "Required Based On Occupancy",
        "1. This is the occupant formula in for determining the required means of egress in a covered mall. ",
        "2. The occupant load factor is not required to be less that _____ and must be more than 50. ",
        "3. GLA stands for the following. ",
        "4. ______ and lobbies in Group B, R-1, and R-2 are not required to comply with the provisions for covered mall buildings in Chapter 4. ",
        "5. Anchored buildings are not to be considered as part of: ",
        "6. OLF refers to: ",
        "7. Two exits must be provided for customers if the distance of travel is more than ____ feet. ",
        "8. All tenant aresas, including areas used for storage, must be inlcuded in calculating the ________",
        "9. No modifications or changes in occupancy for a covered mall can be made without the approval of whom? ",
        "10. A mall that ends at an anchor building where no other means of exit has been provided is considered? ",
        "11. Within each individual tenant space in a covered mall, the maximum distance of travel cannot be more than ______ feet. ",
        "12. 66 inches is the minimum width of: ",
        "13. Fire ______ reated seperations are not required between tenant spaces and the mall. ",
        "14. A small structure having one or more open sides, used as a newsstand or refreshment stand, is defined as a: ",
        "15. Sprinkler protection must be independent from systems provided for tenant spaces or _______",
        "16. Children's playground structures may not be more than _______ square feet in area, unless special investigation has shown satisfactory safety. ",
        "17. Horizontal sliding or ______ security ",
        "18. Covered mall buildings more than 50,000 square feet in area must be provided with _______",
        "19. ________ cannot take up more than 20 percent of the wall area facing the mall. ",
        "20. A bulding with an occupied floor located more than 75 feet above the lowest level is considered to be: ",
        "21. _________ control is not required for atriums that connect only two stories. ",
        "22. The interior finish of walls and ceilings is an atrium cannot be less than Class ______ with no reduction in class for sprinkler systems. ",
        "23. Building spaces having a floor level ",
        "24. Private garages and carports are classified as which group? ",
        "25. Carports must have at least ______ open side(s). ",
        "TRUE/False: REQUIREMENTS ON OCCUPANCY",
        "1. Parking garages are classified as enclosed only",
        "2. Vehcile ramps are not required unless pedestrain facilities are provided. ",
        "3. Asphalt parking surfaces are permitted at at groud level. ",
        "4. Parking garages are not to be considered seperated from other occupancies. ",
        "5. Sleeping areas are permitted to have an opening from a parking garage. ",
        "6. Parking garages are not to be used as spaces to repair vehicles of any kind. ",
        "7. A mechanical ventilation system must be provided for a parking garage. ",
        "8. Repair garages must be constructed in accordance with the International Mechanical Code. ",
        "9. Repair garages must be ventilated in accordance with the International Fire Code. ",
        "10. Institutional facility occupancies are classified as group I-2. ",
        "11. Spaces for doctors' and nurses' stations, charting, communications, and related clerical areas are permitted to be open to the corridor when constructed as such. ",
        "12. Gift shops that are more than 500 square feet in area are permitted to be open to the corridor. ",
        "13. Corridor walls are not required to be constructed as smoke partitions. ",
        "14. Doors to resident sleeping units must have a clear width of not less than 28 inches",
        "15. A fly gallery is a display of exotic flies found around the country ",
        "16. Combustible materials used in sets and scenerios on stages and platforms must meet the fire performance criterial of NFPA 701. ",
        "17. Stages higher than 50 feet must be seperated from dressing rooms, scene docks, and property rooms. ",
        "18. Hazardous materials that are classified as Group H must comply with the International Hazard Code. ",
        "19. Rooms, areas, or spaces in Group H in which explosives, corrosives, and combusistibles are stored must be mechanically vented in accordance with both the International Fire Code and the International Hazard Code. ",
        "20. Group H occupancies must be provided with an automatic fire-detection system. ",
        "21. Flammable vapors or fumes are defined as a concentration of flammable materials exceedings 30 percent of their lower famibility unit. ",
        "22. IDLH stands for 'immediately dangerous to lives and health'",
        "23. Hazardous production material, or HPM, liquid is classified as either Class I flammable liquid or Class ",
        "24. Hydrogen cutoff rooms are not to be located below grade level. ",
        "25. All hydrogen cutoff rooms must have mechanical ventilation and gas-detection systems connected to a standby power system. ",
        "General Building Heights and Areas",
        "1. Address numbers must be _______ numbers or _______ letters. ",
        "2. The building heights is the _______ distance from grade plane to the average height of the highest roof surface. ",
        "3. An intermediate level or levels between the floor and ceiling of any story is defined as a ________",
        "4. The area of a one-story, Group B, F, M or ____ building is not to be limited when the building is equiped with an automtic sprinkler. ",
        "5. The area of a one-story, group A-3 building is not to be limited if the building does not have a _____ other than a platfrom. ",
        "6. A basement is considerd to be a story above grade plane if the finsished surface of the floor above it is more than ____ feet above the finshed ground. ",
        "7. ______ numbers must be a minimum of 4 inches high wiht a minimum width of 0.5 inch. ",
        "8. Two or more buildings on the same lot are to be regulated as ______",
        "9. Motion-picture theaters are a __________construction",
        "10. ________ rooms are required to have a 2-hour seperation and an automatic sprinkler system. ",
        "11. An ______ elevated platform is an unoccupied platform used for mechanical systems. ",
        "12. ________ plane is defined as a reference plance representing the average of finshed ground levels adjoining the building at outside walls. ",
        "13. The height of a one-story ___________ hangars is not limited if the building has an autmotic fire-extinguishing system in accordance with the code",
        "14. The clear height above and below the mezzanine-floor construction cannot be less than ______ feet. ",
        "15. In industrial facalities, mezzanines used for control equipment are permitted to be _________ on all sides",
        "16. The area of a one-story, Group F-2 or S-2 building is not limited when the building is surrounded and adjoined by public ways or yards no less than ______ feet wide. ",
        "17. An automatic sprinkler system is not required for indoor sports, such as _________ , provided that exit doors lead directly outside and there is a fire alarm system. ",
        "18. Buldings must have approved address numbers in place so that they are _________",
        "19. For a basement to be considered as a story, the finished surface of the floor above the basement must be more than ________ feet above the finished ground level. ",
        "20. Storage and laundry rooms both require a _____ - hour seperation or an automatic fire extinguishing system. ",
        "General Building Heights And Areas",
        " 1. Towers, spires, and other roof structures can be used as living space or storage. ",
        " 2. Roof structures are limited in height if they are made of combustible materials and are more than 200ft tall. ",
        "3. Equipment platforms and mezzanines inclue walkways, stairs and ladder",
        "4. Equipment platforms must be fully protected by sprinklers. ",
        "5. Buildings do not have to connect to a public way to recieve an increase in frontage. ",
        "6. Seperate occupancies are individually classified. ",
        "7. The height and number of floors above the basement in an enclosed parking garage are unlimited. ",
        "8. Enclosed garages are allowed to have an office and/or waiting room. ",
        "9. A building height is the horizontal distance from grade plane to the height of the highest roof surface. ",
        "10. Special industrial occupancies are defined as buildings that require larege areas and unusual heights for accommodation of machinery and equipment. ",
        "Types of Construction",
        "1. The 2006 Build Code contains ________ construction types. ",
        "2. Wood columns must be _______, laminated, or sawn and no less than 8 inches in any dimension when used to support floor loads. ",
        "3. Wood beams or _________ must be sawn or glued-laminated timber and not be less than 6 inches in width or less than 10 inches in dpeth. ",
        "4. Framed timber trusses that support floor loads must not have members of less than _______ nominal inches in any dimension. ",
        "5. _________ plates cannot be less than 3 inches in thickness. ",
        "6. Floors cannot have _______ spaces. ",
        "7. ___________ must be made of solid wood construction formed by not less than two layers of 1 inches boards. ",
        "8. The use of combustible piping materials is permitted when installed in accordance with which of the following groups of code. ",
        "9. When using electrical wiring methods, combustible insulation or tubing must be installed in accordance with: ",
        "10. Floors cannot extend closer than ________ to walls. ",
        "True or False",
        "1. Fire-retardant wood framing that complies with this code is permitted within exterior-wall assemblies of a 2-hour rating or less ",
        "2. Columns are to be continous or superimposed and connected in an approved manner. ",
        "3. It is OK to use corbeling in place of molding for masonary walls under the floor. ",
        "4. Columns and arches that conform to heavy to heavy ",
        "5. Structural elements and exterior and interior walls in a Type II construction can be made of any materials. ",
        "6. Fire-retardant-treated wood is permitted in nonbearing paritions where the required fire-resistence rating is 2 hours or less. ",
        "7. An exception to question 6 exists in buildings of Type I, where fire-retardant-treated wood is not permitted if the vertical distance from the upper floor to the roof is less than 20 feet. ",
        "8. Thermal and accoustical insulation, other than foam plastics, must have a flame-spread index of not more than 25",
        "9. Roof coverings that have an A, B, or C classification are permitted to have thermal and accoustical insulation with a flame index of more than 25. ",
        "10. The Type III construction the outside walls must be of noncombustible materials, and the inside building elements are of any materials. ",
        "FIRE REISTANCE RATED CONSTRUCTION",
        "1. _________ is the opening around the penetrating item. ",
        "2. A _____________ is the period of time that an opening protective assembly will maintain the ability to confine a fire. ",
        "3. __________ is building material installed to resist the free passage of flames ",
        "4. Shaft enclosures are the ________ or construction elements forming the boundaries of a shaft. ",
        "5. Openings in exterior walls must be seperated ________ to protect against fire spread on the outside of a building. ",
        "6. A ________ is a type barrier that must be provided on the the outside walls buildings. ",
        "7. Except for _______ construction, fire walls must be made of noncombustible materials. ",
        "8. Fire-resistence-rated glazing must be tested in accodance with _________",
        "9. Walls seperating dwelling units in the same building must comply with fire ______ codes. ",
        "10. A 1-hour fire-resistence-rating is required for smoke barriers except for those barriers that are 0.10 inch-thick steel in Gourp _______ buildings ",
        "11. Smoke-barrier walls are not required in ________ spaces that are designed and constructed with ceilings that provide resistence form fire smoke. ",
        "12. Doors in smoke partitions must not include ______",
        "13. Where required, doors in smoke partitions must be ______ - or automatic closing. ",
        "14. The space around penetrating items and in _______ must be filled with an approved material to limit the passage of smoke. ",
        "15. In 1-hour fire-resistence-rated floor construction, the ceiling ________ is not required to be installed over usuable crawl spaces. ",
        "16. Floor penetrations contained and located within the cavity of a wall do not require a _________",
        "17. Pipes, _________, and conduits must not be embedded in the required fire-protective covering of a structural member that is required to be encasesd. ",
        "18. ______________ is pivoted swinging doors must be tested in accordance with NFPA 252 or UL 10C. ",
        "19. Fire doors must diplay _________ that must be permanently attached to the door or frame. ",
        "20. Unless otherwise permitted, single fire door must have an active _______ bolt that secures the door when closed. ",
        "21. Doors through which pedestrains travel must be activated by __________ with alrm verification. ",
        "22. ________ fire shutters must include autmotic-closing devies. ",
        "23. The size limitation for a fire-protection-rating glazed windo is ______ percent of the area of a common wall in any room. ",
        "24. ________ on a glazing label represents the fire-protection-rating period, in minutes, that was tested. ",
        "25. Fire dampers for hazardous exhaust systems must comply with the __________",
        "Fire-Resistence-Rated True-False",
        "1. Fire blocking is not required for slab-on-grade floors in gymnasiums. ",
        "2. Draft stopping is required in buildings equipeed with an automtic sprinkler system. ",
        "3. Draft stopping doesn't have to be installed in concealed proof spaces as long as they are larger than 3,000 square feet. ",
        "4. Unsanded gypsum is considered equal to gypsum sand plaster if mixed properly. ",
        "5. Fiberboard insulation is the smae as foam plastic insulation. ",
        "6. A ceramic fiber blanket is defined as a lightweight insulating material consisting of inorganic fiber glass formed into rigid boards. ",
        "7. The thickness of panels with tapered cross sections is determined at a distance of 6 inches from the edge. ",
        "8. Joints between adjacent precast concrete slabs are to be considered in calculating the slab thickness provided that a concrete topping of at least 1 inch is used. ",
        "9. F rating is the letter classification given to fire-resistence-rated materials. ",
        "10. A fire seperation distance is the imaginary line to a street, alley, or public way. ",
        "11. A window constructed and glazed to give protection against the passage of fire is a fire window assembly. ",
        "12. An opening that passes through an entire assembly is called a passageway. ",
        "13. Cornices, eave overhangs, and exterior balconies are just three examples of exterior walls. ",
        "14. Type V construction is allowed for R-3 occupancies. ",
        "15. Exterior wals must be of materials allowed by the building's type of construction. ",
        "16. A lightweight insulating concrete made by mixing preformed foam with Portland-cement slurry is considered to be perlite concrete. ",
        "17. When rating structured-steel columns for fire resistence, the rating must be based on the size of the element and the type of protection. ",
        "18. W/D means weight-to-heated perimter rations. ",
        "19. When equating the fire resistance of structural steel, 'R' refers to the fire resistance rating of column and assebmly (in hours).",
        "20. It doesn't really matter how concrete is mixed or what it is mixed with as long as it suits your purposes. ",
        "21. Fire-resistance rating calculated using the code book must be used for 1-hour rated assemblies. ",
        "22. Membranes have assigned times on the fire-exposed side. ",
        "23. Allowable loads on beams and columns are determined using design values given in AF&PANDS",
        "24. Wood members do not have a minimum size requirement. ",
        "25. The time assigned to double 3/8 inch gypsum wallboard is 40 minutes. ",
        "Interior Finishes",
        "1. Show windows in the exterior walls of the first story above grade shall _____ permitted to be of wood. ",
        "2. Show windows in the exterior walls of the first story above grade shall _____ permitted to be of unprotected metal framing. ",
        "3. The propagation of flame over a surface is known as ________",
        "4. Interior finishes include ________",
        "5. The exposed floor surfaces of buildings, including covering applied over a finshed floor or stair, including risers, are known as _______",
        "6. Trim can include _________",
        "7. Trim can include _________",
        "8. Trim can include _________",
        "9. Trim can include _________",
        "10. An interior wall or ceiling finish that is not more than _______ inch thick shall be applied directly against a noncombustible backing. ",
        "True or False",
        "1. Combustible materials shall not be permitted for use as a finish for walls, ceilings, floors, and other interior surfaces of buildings. ",
        "2. Foam plastics shall not be used as an interior finish or trim. ",
        "3. Expanded-vinyl wall covering is a wall covering that consists of woven textile backing, an expanded vinyl base-coat layer, and a nonexpanded vinyl skin coat. ",
        "4. Combustible insulating boards are not permitted to be attached directly to a noncombustible floor assembly. ",
        "5. Textile wall and ceiling coverings shall have a Class A flame-spread index. ",
        "6. Interior-finish materials regulated by the code shall be ",
        "7. The stability of interior-finish materials must be capable of withstanding a temperature test for not less than 60 minutes. ",
        "8. A Class C rating applies to materials with a flame-spread index of 76 to 200. ",
        "9. A Class A rating rating applies to materials with a flame-spread index of 0 to 25. ",
        "10. A Class B rating applies to materials with a flame-spread index of 26 to 75",
        "Fire-Protection Systems",
        "1. Automatic sprinkler systems shall be monitored by ________",
        "2. A fire-alarm-system component such as ________ or any combination thereof defines an alarm notification appliacne. ",
        "3. A fire-alarm-system component such as _______ or any combination thereof defines an alarm notification appliance. ",
        "4. A fire-alarm system component such as _______ or any combination thereof defines an alarm notification appliance. ",
        "5. An ammuinciator is a unit containing one or more indicator lamps, alphanumeric displays, or other equivalent means in which each indication provides status information about a _______",
        "6. Automatic, as applied to fire-protection devices, refers to a device or system providing an emeregency function without the neciessity for human inteverion and is activated as a result of predetermined __________",
        "7. Automatic, as applied to fire-protection devices, refers to a device or system that provides an emergency function without the necessity for human intervention and is activated as a result of a pre-determined _________",
        "8. Automatic sprinkler systems are usually activated by ______ and discharge water over the fire area. ",
        "9. Electricaly nonconducting, volatile, or gaseous fire-extinguishing chemicals that do not leave a residue upon evaporation are known as _________",
        "10. A fire command center is the principal _________ location where the status of detection, alarm communications, and control systems are displayed. ",
        "11. A foam-extinguishing system is a special system discharging a foam made from concentrates spread _________",
        "12. Halogenated extinguishing systems are fire-extinguishing systems using one or more atoms of an element from the haologen chemical series",
        "13. Halogenated extinguishing systems are fire-extinguishing systems using one or more atoms from the halogen chemical series of ________",
        "14. A Class I standpipe system is one that provides ________ hose connections to supply water for use by fire departments and those trained in handling heavy fire streams. ",
        "15. A Class II standpipe system is one that provides",
        "16. A Class III standpipe system is one that provides ______ hose connections to supply water for use by fire departments and those trained in handling heavy fire streams. In addition to the hose connections, a Class III system provides 1.5 inch hose stations for use by building occupants and the fire department. ",
        "17. Types of standpipes systems may include __________",
        "18. Types of standpipe systems may include _________",
        "19. Types of standpipe systems may include ________",
        "20. Types of standpipe systems may include ________",
        "21. The bulk storage of tires is described as tire storage where the area avaliable for storage exceeds ________ cubic feet. ",
        "22. An automatic sprinkler system shall be provided throughout buildings and portions thereof used as ______ occupanices as provided for in the code. ",
        "23. An automatic sprinkler system shall be provided for Group A-1 occupancies where the fire area exceeds _______ square feet. ",
        "24. An automatic sprinkler system shall be provided for Group A-1 occupancies where the fire area has an occupant load of _______ or more. ",
        "25. An automoatic sprinkler system shall be provided for Group A-1 occupancies where the fire area is located on a _______ other than the level of exit discharge. ",
        "26. An automatic sprinkler system shall be provided for Group A-1 occupancies where the fire area contains ______",
        "27. An automatic sprinkler system shall be provided for Group A-2 occupancies where the fire area contains ________",
        "28. An automatic sprinkler system shall be provided for Group A-2 occupancies where the area has an occupant load of _______ or more. ",
        "29. An automatic sprinkler system shall be provided for Group E occupancies where the areas greater than ________ square feet. ",
        "30. An automatic sprinkler system shall be provided for Group E occupancies where the areas are greater than _______ square feet. ",
        "31. An automatic sprinkler system shall be provided throughout all buildings containing a Group F-1 occupancy where the fire area exceeds ________ square feet. ",
        "32. An automatic sprinkler system shall be provided throughout all buidlings containing a Group F-1 occupancy where the fire area is located more than _______ stories above grade. ",
        "33. An automatic sprinkler system shall be provided throughout all buildings containing a Group F-1 occupancy where fire areas on all floors, including mezzanines, exceed _________ square. ",
        "34. An automatic sprinkler sytstem shall be provided throughout all buildings containing a Group F-1 occupancy where fire areas contain woodworking operations in excess of ________",
        "35. An automatic sprinkler system shall be provided in buildings, or in portions thereof, where celuose-nitrate film or pyroxylin plastics are manufactured, stored, or handled in quantities exceeding ______ pounds ",
        "36. Where required by the International Mechanical Code, automatic sprinklers, with some exceptions, shall be provided in ducts converying _________",
        "37. Where required by the Internaional Mechanical Cocde, automatic sprinklers, with some exceptions, shall be provided in ducts conveying _______",
        "38. No less than a _________-foot clearance shall be maintained between automatic sprinklers and the top of piles of combustible fibers. ",
        "39. Automatic sprinklers shall be installed in or under covered ________ that exceeds 4 feet in width. ",
        "40. Automatic sprinklers shall be installed in or under covered _________ that exceed 4 feet in width. ",
        "41. Automatic sprinklers shall be installed in or under covered ________ that exceeds 4 feet in width. ",
        "42. Automatic sprinklers shall be installed in or under covered ________ that exceeds 4 feet in width. ",
        "43. Automatic equipment interlocks for automatic fire systems may include ________",
        "44. Automatic equipment interlocks for automatic fire systems may include ________",
        "45. Automatic equipment interlocks for automatic fire systems may include ________",
        "46. Construction documents for fire-alarm systems shall be submitted for review and approval prior to system installation.  The documents shall include ________",
        "47. Where ________ conditions prohibit installations of automatic smoke detection, other automatic detection shall be allowed. ",
        "48. A manual fire-alarm system shall be installed in Group B occupancies having an occupant load of ______ or more persons or more than 100 persons above or below the lowest level of exit discharge. ",
        "49. Buildings with a rating of Group I-3 shall be equipped with both manual and automatic fire-alarm systems for alerting ________",
        "50. Group R-1 occupancies require the installation of _________ fire-alarm system. ",
        "Fire Protection Systems True and False",
        "1. Threads provide for fire-department connections to sprinkler systems, standpipes, yard hydrants, or any other fire-hose connection shall be compatible with the connections used by local fire departments. ",
        "2. A supervising station is not required for automatic sprinkler systems protecting single-family homes. ",
        "3. A supervising station is not required for automatic sprinkler systems protecting two-family homes. ",
        "4. Manual fire-alarm, automatic fire-extinguishing, and emergency-alarm systems in Group H occupancies shall be monitored by an approved supervising station. ",
        "5. An alarm signal is a signal indicating an emergency requiring immediate action. ",
        "6. Alarm verification appliance features are designed to log in response time to emergencies. ",
        "7. A notification appliance that alarts through the sense of hearing is known as an audible alarm-notification appliance. ",
        "8. An automatic fire-extinguishing system is an approved system of devices and equipment that automatically detects a fire and sounds an alarm. ",
        "9. Carbon-dioxide extinguishing systems are systems that include manual or automatic actuating mechanism. ",
        "10. A deluge system is one in which, when a valve is opened, water flows into the piping system and discharges from all spinklers attched heretherto. ",
        "11. Heat is the energy produced by combustion that causes substances to drop in temperature. ",
        "12. An effect produced by the sudden violent expansion of gases and accompanied by a shock wave, disruption of enclosing materials of structures, or both is known as flash-out fire. ",
        "13. A smoke detector is an example of an initiating device. ",
        "14. A nuisance alarm can be an alarm that is activated by a cause that cannot be determined.",
        "15. A trouble signal is a signal initiated by the fire-alarm system or device of indictive of a fire with flame spread. ",
        "16. A wet-chemical extinguishing system is one that uses a solution of water and a potassium-carbonate-based chemcial, or a combination thereof that forms an extinguishing agent. ",
        "17. A zone is a defined area within the protected premises. ",
        "18. An automatic sprinkler system shall be installed in Group H occupancies. ",
        "19. An automatic sprinkler system is not required for Group I-1 facilities. ",
        "20. Areas for the bulk storage of tires are required to be equipped with automatic sprinkler system. ",
        "21. Basements containing 1,500 square feet may be subject to the installation of an automatic sprinkler system. ",
        "22. Kitchen exhaust hoods in commerical cooking operations are required to be with an automatic sprinkler system. ",
        "23. Sprinklers may be omitted from any room that is damp, is of fire-resistance-rated constuction, or contains electrical equipment. ",
        "24. Fire-hose threads and fittings used in connection with automatic spinkler systemes shall be prescribed by the local building official. ",
        "25. Approved audible dieces shall be connected to every automatic sprinkler styem. ",
        "26. Alarm devices shall be provided on the interior of the buildings and are recommended on the exterior of buildings. ",
        "27. Approved control valves shall be provided at the point of connection to the riser on each floor in high-rise buildings. ",
        "28. Aumomatic sprinkler protecting commercial-type cooking equipment shall be supplied from a seperate, readily accessible, indicating-type control valve that is identified. ",
        "29. Stages greateer than 1,500 square feet in area shall be equipped with a Class III wet standpipe system. ",
        "30. Underground buildings shall be equiped throughout with a Class I autmoatic or manual wet standpipe system. ",
        "31. In Group I-1 buildings, corridors, habitable spaces other than sleeping units and kitchens and waiting areas that are open to corridors shall be equiped with an automatic smoke-detection system. ",
        "32. Smoke detector in high-rise buildings are to be connected to an automatic fire-alarm system. ",
        "33. Manual overrides for emergency voice communication shall not be allowed. ",
        "34. Covered mall building exceeding 35,000 square feet in total floor area shall be provided with an emergency voice-alarm communication system. ",
        "35. An approved automatic smoke-detection system shall be installed in areas containing stationary storage-battery systems having liquid capacity of more than 50 gallons. ",
        "36. A presignal system shall not be be installed unless approved by the fire-code official and the fire department. ",
        "37. Each floor shall be zoned separately, and a zone shall not exceed 20,000 square feet. ",
        "38. Visible alarm-notification appliances shall be provided in public areas and common areas. ",
        "39. Duct smoke detectors shall have an independent alarm that is not connected to the building's fire-alarm control pannel. ",
        "40. Smoke-control systems are exempt from the building code.",
        "41. Vestibule ventilation shall have a minimum net area of 8 square feet. ",
        "42. The vestibule ceiling shall be at least 24 inches higher than the door opening into a vestibule to serve as a smoke and heat trap. ",
        "43. Smoke and heat vents shall be capable of being operated by approved automatic and manual means. ",
        "44. The effective venting area for smoke and heat vents shall not be less than 16 square feet. ",
        "45. A metal sign with raised letters at least 1 inch in size shall be mounted on all fire-department connections serving automatic sprinklers, standpipes, or fire pump connections. ",
        "Means of Egress",
        "1. An alternating tread device is one that has a series of steps between 50 and _____ degrees from horizontal, usually attached to a center support rail in an alternating manner so that the user does not have both feet on the same level at the same time.",
        "2. Tiered seating facilities are known as ______",
        "3. An enclosed exit-access component that defines and provides a path of egress travel to an exit is known as ______. ",
        "4. A door equipped with double-pivoted hardware so designed as to cause a simi-counterbalanced swing action when opening is knows as a _______",
        "5. Panic hardware that is listed for use on fire-door assemblies is called ________",
        "6. The actual occupied area not including unoccupied accessory areas such as corridors, stairways, toilet rooms, mechanical rooms, and closets is knows as the _______",
        "7. Tiered seating facilities can be referred to as ________",
        "8. The leading edge of treads of stairs and of landings at the top of stairway flights is known as ______",
        "9. A ramp is a walking surface that has a running slope steeper than a _______- percent slope. ",
        "10. Two interlocking stairways providing two seperate paths of egress located within  one stairwell enclosure are known as _______",
        "11. The means of egress shall have a minimum ceiling height of _______",
        "12. Door closers and stops shall not reduce headroom to less than ______ inches. ",
        "13. A freestanding object mounted on a post or pylon shall not overhang that post or pylon more than _____ inches where the lowest point of the edge is more than 27 inches and less than 80 inches above the walking surface. ",
        "14. Where changes in elevation of less than _____ inches exist in the means of egress, sloped surfaces shall be used. ",
        "15. When changes in elevation on a means of egress are _____ inches or less, the ramp shall be equiped with either handrails or floor-finsihed materials that contrast the adjacent floor finshed materials. ",
        "16. In order to be considered part of an accessible means of egress, an exit stairway shall have a clear width of ______ inches minimum between the handrails and shall either incorporate an area of refuge within an enlarged floor-level landing or shall be accessed from either an area of refuge within an enlarged floor-level landing or shall be accessed from either an area of refuage complying with Section 1007.6 of a horizontal exit. ",
        "17. Areas of refuge shall be provided with a(n),________ system between the area of refuge and a center control point. ",
        "18. The exterior for assisted rescue shall be at least _______ perecent open, and the open area above the guards shall be so distrubuted as to minimize the accumlation of smoke or toxic gases. ",
        "19. The minimum width of each door opening shall be sufficient for the occupant load thereof and shall provide a clear width of not less than _____ inches. ",
        "20. Projections into clear width areas shall not be lower than _______ inches above the floor or ground. ",
        "21. Revolving doors shall not be given credit for more than ______ percent of the required egress capacity. ",
        "22. Revolving doors shall be credited with no more than a ______ person occupancy. ",
        "23. Each revolving door shall be capable of being collapsed when a force of not more than ______ pounds is applied within 3 inches of the outer edge of a wing. ",
        "24. Thresholds at the doorways shall not exceed _______ inch in height for sliding doors serving dwelling units. ",
        "25. Space between two doors in a series shall be ______ inches minimum, plus the width of a door swinging into the space. ",
        "26. Horizontal sliding or swinging gates exceeding the 4-foot maxium leaf-width limiation are permitted in _______",
        "27. The width of a stairwell shall not be less than _____ inches. ",
        "28. Stair risers shall have a maximum height of _______ inches. ",
        "29. Stair risers shall have a minimum height of _______ inches. ",
        "30. When exceptions are applied, spiral stairways complying with Section 1009.8 are permitted a ______ inch headroom clearance. ",
        "True False for Means of Egress",
        "1. Accessible means of egress is a continous and unobstructed way of travel from any accessible point in a building or facility to a public way. ",
        "2. An exit-access component that defines a and provides a path of egress travel is an aisle",
        "3. An area where persons unable to use stairways can remain temporarily to await instructions or assistance during emergency evacuation is a refuage area. ",
        "4. A court or yard that provides accesss to a public way with no more than one exit is known as an egress court. ",
        "5. An operable window shall not be considered to be an emergency escape and rescue opening. ",
        "6. An exit discharge is that portion of a means-of-egress system between the termination of an exit and a public way. ",
        "7. An exit access is that portion of a means-of-egress system that leads from any occuppied portion of a building or structure to an exit. ",
        "8. A handrail is a vertical rail intended for grasping by the and for guidance or support. ",
        "9. A merchandise pad is an area for display of merchandise surrounded by aisles, permananet fixtures, or walls. ",
        "10. Smoke-protected assembly seating is seating served by a means of egress that is not subject to smoke accumulation within or under a structure.",
        "11. A change in elevation consisting of one or more risers is known as a stiar. ",
        "12. One or more flights of stairs, either exterior or interior, with the necessary landings and platforms connecting them to form a continous and uninterupted passage from one level to another is a stairway. ",
        "13. A winder is a tread with non-parallel edges. ",
        "14. A stairway having an open circular form in its plan view with uniform section-shaped treads is known as a spiral staircase.",
        "15. A public way is required to have a clear width and height of not less than 12 feet. ",
        "16. Protruding objects shall not reduce the minimum clear width of accessible routes. ",
        "17. Walking surfaces on the means of egress shall have a slip-resistant surface and be securely attached. ",
        "18. Escalators, since they can be walked upon without electrical power, shall be considered a means of egress. ",
        "19. The posting of allowable occupant load is required in a place of assembly occupancy. ",
        "20. Each door providing access to an area of refuge from an adjacent floor area shall be identified by a sign. ",
        "21. Egress doors shall not be side-hinged swinging doors",
        "22. There shall be a floor or landing on each side of a door. ",
        "23. Bolt locks are prohibited. ",
        "24. The unlatching of any door or leaf shall not require more than two operations. ",
        "25. Locks may be permitted to prevent operation of doors at places of detention or restraint. ",
        "26. Turnstiles that restrict travel to one direction shall not be placed so as to obstruct any required means of egress",
        "27. Winder treads are prohibited in all stairways used as a means of egress. ",
        "28. Outdoor stairways must be constructed to prevent the accumulation of water on walking surfaces. ",
        "29. Ramps with a rise greater than 6 inches shall have handrails on both sides.",
        "30. The minimum headroom in all parts of a means-of-egress ramp shall not be less than 78 inches. ",
        "Accessibility",
        "1. A site, building, facility, or portion thereof that complies with the accessibility chapter of the code is consider to be _____",
        "2. A continous, unobstructed path that complies with the accessibility chapter of the code is considered to be _______",
        "3. An exterior or interior way of passage for pedestrains from one place to another is called a _______",
        "4. Interior or exterior rooms, spaces, circulation paths, or elements that are not for public use are made avaliable for the shared use of two or more people are known as ______",
        "5. Areas that do not qualify as employee work areas incldue _________",
        "6. Areas that do not qualify as employee work areas include _________",
        "7. Areas that do not qualify as employee work areas include _________",
        "8. All or any portion of buildings, structures, site, improvements, elements, and pedestrian or vehicular routes located on a site can be called ________",
        "9. A restricted entrance is one that is made avaliable for common use on a controlled basis but not for ________",
        "10. A restricted entrance is one that is made avaliable for common use on a controlled basis but not for a _______",
        "11. A service entry is an entrance intended primarily for delivery of ______",
        "12. Detached ______ dwellings and accessory structures and their associated sites are not required to be accessible. ",
        "13. Construction sites, structures, and equipment direclty assocaited with the actual process of the construction including but not limted to ______ are not required to be accesible",
        "14. Construction sites, structures, and equipment direclty associated with the actual process of construction including but not limited to ________ are not required to be accesible. ",
        "15. Construction sites, structures, and equipment directly associated with the actual process of construction indlcuding but not limted to _____ are not required to be accesible. ",
        "16. Raised areas used primarliy for purpses of security, life safety including but not limited to _____ are not required to be accessible or to be served by an accessible route.",
        " 17. Raised areas used primarily for purposes of security, life safety, or fire safety including but not limited to _____ are not required to be accessible or to be served by an accessible route. ",
        "18. Raised areas used primarily for purposes of security, life safety, of fire safety including but not limited to ________ are not required to be accessible or to be served by an accesible route",
        "19. Nonoccupaible spaces accessed only by ______ are not required to be accesible. ",
        "20. Nonoccupiable spaces accessed only by _______ are not required to be accesible. ",
        "21.Nonoccupiable spaces accessed only by _______ are not required to be accesible. ",
        "22. Spaces frequented only by personnel for maintenance, repair, or monitoring of equipment are not required to be accessible.  Such spaces may include ____",
        "23. Spaces frequented only by personnel for maintenance, repair, or monitoring of equipment are not required to be accessible.  Such spaces may include ____",
        "24.Spaces frequented only by personnel for maintenance, repair, or monitoring of equipment are not required to be accessible.  Such spaces may include ____",
        "25. Spaces frequented only by personnel for maintenance, repair, or monitoring of equipment are not required to be accessible.  Such spaces may include ____",
        "26. Spaces frequented only by personnel for maintenance, repair, or monitoring of equipment are not required to be accessible.  Such spaces may include ____",
        "27. Spaces frequented only by personnel for maintenance, repair, or monitoring of equipment are not required to be accessible.  Such spaces may include ____",
        "28. Spaces frequented only by personnel for maintenance, repair, or monitoring of equipment are not required to be accessible.  Such spaces may include ____",
        "29. Spaces frequented only by personnel for maintenance, repair, or monitoring of equipment are not required to be accessible.  Such spaces may include ____",
        "30. Spaces frequented only by personnel for maintenance, repair, or monitoring of equipment are not required to be accessible.  Such spaces may include ____",
        "31. Spaces frequented only by personnel for maintenance, repair, or monitoring of equipment are not required to be accessible.  Such spaces may include ____",
        "32. In multilevel buildings and facilities, at least ________ accesible routes(s) shall connect each accessible level, including mezzanines. ",
        "33. Where provided, _________ access for pedestrains from parking structures to buildings or facility entrances shall be accesible. ",
        "34. With some exceptions, at least one accesible entrance shall be provided to each _____ dwelling unit, and sleeping unit in a facility. ",
        "35. Hospitial parking areas are required to offer _______ perecent of patient and visitor parking spaces provided to serve hospitial outpatient facilities with accesibility.",
        "36. Rehabilitition and outpatient physical-therapy facilities shall have a minimum of one accessible parking space with ________ perecent of the toal parking area being accessible. ",
        "37. For every _____ or faction of ________ accesibile parking spaces, at least one shall be a van accesibile parking space. ",
        "38. Continous loading zones are required where passenger loading zones are provided; one passenger loading zone in every continous ____ linear feet maximum of loading zone space shall be accessible. ",
        "39. A passenger laoding zone shall be provided at an accesible entrance to licensed medical and long-term-care facilities where people recieve physical or medical treatment or care and where the period of stay exceeds ____ hours",
        "40. Nursing homes require at least _____ percent nut not less than one of each type of dwelling and sleeping units to be accessible. ",
        " 41. At least one wheelchair space shall be provided in _______ seating areas, with the exception of seating areas serving bowling lanes or other ares of sport activity. ",
        " 42. When working with designated aisle seats, at least _______ percent but not less than one of the total number of aisle seats provided shall be designated aisle seats. ",
        "43. Acceisble self-storeage storage facilities that have between 1 and 200 storage units are required to have _____ perecent of the spaces but not less than 1 to be accessible. ",
        "44. Where water-closet compartments are provided in a toilet room or bathing facility, the code requires a minimum of a _______",
        "45. When drinking fountains are provided on an extrerior site, or a floor, or within a secured area, no fewer than ______ drinking fountains shall be provided. ",
        "46. Self-service shelves and display units shall be located on __________",
        "47. Passenger transit platform edges bordering a dropoff and not protected by platform screens or guards shall have _______",
        "48. Where dressing rooms, fittings rooms, or locker rooms are provided, at least _____ percent but not less than one of each type of use in each cluster provided shall be accessible. ",
        "49. Food-service lines shall be accesible.  Where self-service shelves are provided, at least ______ percent but not less than one of each type provided shall be accessible. ",
        "50. Raised boxing or wrestling rings ____ required to be accesible. ",
        "Accessibility True or False",
        "1. An accesible unit is a dwelling or sleeping unit that complies with the code and the provisions for accessibility. ",
        "2. A detachable warning is a device used to warn visually impaired persons of hazards on a circulation path. ",
        "3. Multilevel assembly seating is arranged in distinct levels where each level is comrpised of either multiple rows or a single row of box seats accessed from a separate level. ",
        "4. A dwelling or sleeping unit with habitable space located on more than one story is known as a multistory unit. ",
        "5. An entrance that functions as a service entrance is known as a public entrance. ",
        "6. A site is a parcel of land bounded by a lot line or a designated portion of a public right-of-way. ",
        "7. A space for a single wheelchair and its occupant is known as a wheelchair space. ",
        "8. Spaces frequented only by personnel for maitenance, repair, or monitoring of equipment are required to be accessible. ",
        "9. Toll booths are required to be accessible. ",
        "10. If a daycare facility is part of a dwelling unit, only the portion of the structure utilized for the daycare facility is required to be accessible. ",
        "11. In detention, or correctional facilities, common-use areas that are used by only inmates or detainees and security personel, and that do not serve accessible holding cells or housing cells are required to be accessible. ",
        "12. In detention and correctional facilities, common-use areas that are used only by inmantes or detainees and security personnel, and that do not serve accessible holding cells or housing cells are required to be served by an accesible route. ",
        "13. Walk-in coolers and freezers intended for employee use only are not required to be accessible. ",
        "14. At least one accessible route shall connect accessible buildings, accesible facilities, accessible elements and accessible elements, and accessible spaces on the same site.",
        "15. An accessible route is not required between accessible buildings, accessible facilities, accessible spaces that have, as the only means of access between them, a vehicular way that does not provide for pedestrain access. ",
        "16. With some exceptions, common-use circulation paths within employee work areas shall be accesible routes. ",
        "17. Where direct access is provided for pedestrains from a pedestrain tunnel or elevated walkway to a building or facility, at least two entrances to the building or facility from each tunnel or walkway shall be accessible. ",
        "18. Where restricted entrances are provided to a building or a facility, at least one such entrance to the building or facility shall be accessible. ",
        "19. Where entrances used only by inmates or detainees and security personnel are provided at the judicial, detention, or correctional facilities, at least one such entrance shall be accessible. ",
        "20. Service entrances shall be excempt from accesibly under all condition. ",
        "21. An accessible entrance is not required for tenants in buildings not required to be accessible. ",
        "22. Accesible parking spaces shall be located on the shortest accesible route of travel from adjacent parking to an accessible building entrance. ",
        "23. A passenger loading zone shall be provided at locations of vlet parking services. ",
        "24. At least one accessible route shall connect accessible building or facility entrances with the primary entrance of each accessible unit. ",
        "25. Lawn seating areas and exterior overflow seating areas, where fixed seats are not provided, shall not connect to an accessible route. ",
        "Interior Environment Question",
        "1. A one-story addition to an existing building with a glazing area in excess of 30 percent of the gross area of the structure's exterior walls and roof is a sunroom addition.",
        "2. A one-story addition to an existing building with a glazing area in excess of 40 percent of the gross area of the structure's exterior walls and roof is a sunroom addition. ",
        "3. A two-story addition to an existing building with a glazing area in excess of 40 percent of the gross area of the structure's exterior walls and roof is a sunroom addition. ",
        "4. A separtion of conditioned spaces between a sunroom addition and a dwelling unit consisting of existing or new wall(s), doors, and/or windows is known as thermal isolation.",
        "5. Enclosed attics and enclosed rafter spaces formed where ceilings are applied direclty to the underside of roof framing members shall have cross-ventilation for each sepearte space by means of ventilating openings against the entrance of rain and snow ",
        "6. Blocking and briding in an enclosed attic shall be arranged so as not to interfere with the movement of air. ",
        "7. A minimum of 2 inches is required between attic insulation and roof sheathing. ",
        "8. The net free ventilating area of an enclosed attic shall not be less than 1/150 of the area of the space ventilated, with 50 percent of the required ventilating area provided by ventilators located in the upper portion of the space to be ventilated at least 3 feet above the eave or cornice vents and the balance of the required ventilation provided by eave or cornice vents. ",
        "9. Exterior openings into attic space of any building intended for human occupancy shall be covered with corrision-resistent wire cloth screening, hardware cloth, perforated vinyl, or similar material. ",
        "10. The space between the bottom of the floor joist and the earth undr any building, except space occupied by a basement or ceiling, shall be provided with ventilation openings through foundation or exterior walls. ",
        "11. Ventilation is under floor applications is prohibited from causing cross ventilation. ",
        "12. The minumum net area of ventilation opening for under floor ventilation openings for under floor ventilation shall not be less than 200 square foot of crawl-space. ",
        "13. Natural ventilation of an occupied space shall be through windows, doors, louvers, or other openings of the outdoors. ",
        "14. Operating mechanisms for natural-ventilation openings shall be provided with ready access. ",
        "15. The minimum openable area to the outdoors for natural ventilation shall be 8 percent of the floor area being ventilated. ",
        
        "16. Where rooms and spaces without openings to the outdoors are ventilated through an adjoining room, the opening to the adjoining room shall be unobstructed and shall have an area of not less than 4 percent of the floor area of the inteiro room or space and not less than 25 square feet. ",
        "17. Where openings below grade provide required ventilation, the outside horizontal clear space measured perpendiuclar to the opening shall be one and one-half times the depth of the opening. ",
        "18. Rooms containing bathtubs, showers, spas and other similiar bathing fixtures shall be mechanically ventilated in accordance with the International Mechanical Code and the International Fire Code. ",
        "19. Interior Spaces intended for human occupancy shall be provided with active or passive space-heating systems. ",
        "20. Ratings for temperature control in buildings intended for human occupancy require heating ystmes to maintain indoor temperature of 72 degrees F at a point 3 feet above the floor on the design heating day. ",
        "21. When used to meet requirements for natural light, the minimum net glazed area shall not be less than 8 percent of the floor area of the room served. ",
        "22. For the purpsose of natural lighting, any room may be considered as a portion of an adjoining room where one-half of the area of the common wall is open and unobstructed and provides an opening of not less than one-tenth of the floor area of the interior room or 25 square feet, whichever is greater. ",
        "23. Artificial light shall be provided that is adequate to provide an average illumination of 8 foot candles over the area of the room at a height of 30 inches above the floor level. ",
        "24. Stairways within dwelling units and exterior stairways serving a dwelling unit shall have an illumination level on the tread run of not less than 1 footcandle. ",
        "25. Yards for on and two story buildings must have a minimum width of 5 feet. ",
        "26. For buildings more than two stories in height, the minimum width of the yard shall be increased at the rate of 1 foot for each additional story up to 14 stories. ",
        "27. When dealing with court areas, acess shall be provided to the bottom of the courts for cleaning purposes. ",
        "28. Courts more than two stories in height shall be provided with a vertical air intake at the bottom not less than 10 square feet in area. ",
        "29. The bottom of every court shall be properly garded and drained. ",
        "30. Habitable spaces other than kitchens shall not be less than 8 feet in any plan dimension. ",
        "31. Kitches shall have a clear passageway of not less than 3 feet between counter fronts and appliances or counter fronts and walls",
        "32. Occupiable spaces, habitable spaces, and corridors shall have a cieling height of not less than 8 feet. ",
        "33. Bathrooms may have a minimum ceiling height of 7 feet. ",
        "34. Kitches may have a minimum ceiling height of 7 feet. ",
        "35. Laundry rooms may have a minimum ceiling height of 6 1/2 feet. ",
        "36. Storage rooms may have a minimum ceiling height of 6 1/2 feet. ",
        "37. Any room with a furred ceiling shall be required to have the minimum ceiling height in one third of the area served. ",
        "38. Every dwelling unit shall have at least one room that shall have not less than 120 square feet of net floor area. ",
        "39. Every kitchen in one and two family dwellings shall have not less than 50 square feet of gross floor area. ",
        "40. Crawl spaces shall be provided with a minimum of one access opening not less than 18 inches by 24 inches. ",
        "41. An opening not less than 18 inches by 24 inches shall be provided ito an atic area. ",
        "42. A 30 inch minimum of clear headroom shall be provided at or above the access openings in an attic space. ",
        "43. In units other than dwelling units, toilet and bathing-room fllors shall have a smooth, hard, nonabsorbent surface that extends upward onto the walls at least 6 inches",
        "44. Walls within 3 feet of urinals and water closets shall have a smooth, hard, nonabosrbant surface, to a height of 4 feet above the floor, and expect for  structural elements the matieral used in such walls shall be a type that is not adversley affected by moisture. ",
        "45. Shower compartments and walls above bathtubs with installed shower heads shall be finsished with a smooth, nonabsorbant surfact to a height not less than 72 inches above the drain intlet. ",
        "46. Built-in tubs with showers shall have waterproof joints between the tub and adjacent wall. ",
        "47. Any room for the preperation of food for service to the public shall have a toilet room that opens directly into the food-preperationl area. ",
        "48. Grab bars in bathrooms are required to be installed and sealed to protect structural elements from moistuere. ",
        "49. An efficeincy dwelling unit shall have a living room of not less than 220 square feet of floor area. ",
        "50. Effeciency dwelling units are required to have a minimum of one seperate closet. ",
        "Exterior Walls",
        "1. Veneer secured and supported through the adhesion of an approved boudning material applied to an approved backing creates an _________ masonry veneer",
        "2. Veneer secured with approved mechanical fasteners to an approved backing is known as ________ masonry veneer.",
        "3. The wall or surface to which veneer is secured is known as _________",
        "4. An exterior wall is a wall, nonbearing, that is used as an enclosure for a building other than a fire wall, and that has a slope of _______ degrees with the horizontal plane. ",
        "5. Metal composite material systmes consist of an exterior-wall finish system fabricated using MCM in a specific assembly including ______",
        "6. Metial composite materials systems consist of an exterior-wall finish system fabricated using MCM in a specific assembly including ________",
        "7. Metal composite material systems consist of an exterior-wall finsh system fabricated using MCM in a specific assembly including _______",
        "8. Metal composite material systems consist of an exterior-wall finish system fabricated ",
        "9. Metal composite material systems consist of an exterior-wall finish system fabricated using MCM in a specific assembly including _______",
        "10. Veneer is a facing attached to a wall for the purpose of providing _______",
        "11. Veneer is a facing attached to a wall for the prupose of providing _______",
        "12. Exterior-wal envelope test assemblies shall be at least 4 feet by ____ feet in size.",
        "13. Exterior-wall-envelope assemblies shall be tested at a minimum differential pressure of _____ pounds per square foot. ",
        "14. Exterior-wall-envelope assemblies shall be subjected to a minimum test exposure duration of _________ hours. ",
        "15. Masonry walls require _______ to be installed in the first course above the finished ground level above the foundation. ",
        "16. Stone veener units not exceeding ____ inches in thickness shall be anchored directly to masonry, concrete, or stud construction. ",
        "17. Veneer units of marble, traverine, granite, or other stone units of slab form ties of corrosion resistent dowels in drilled holes shall be located in the middle third of the edge of the units and paced at maximum of ______ inches aprt around the periphery of each unit with not less than four ties per veneer unit. ",
        "18. Interior adhered masonry veneers shall have a maximum weight of ______ psf. ",
        "19. Metal veneers that are not constructed of approved corrosion-resistent materials shall be protected front and back with______ ",
        "20. Exterior metal veneer shall be securely attached to the supporting masonry or framing members with _______",
        "21. Methods for protecting metal supports for exterior metal veneer against weather include ________ ",
        "22.  The areas of a single section of thin exterior structural-glass veneer shall not exceed _____ square feet where the section is not more than 15 feet above the level of a sidewalk or grade level directly below. ",
        "23. The areas of a single section of thin exterior structural-glass veneer shall not exceed _______ square feet where the section is more than 15 feet above the level of a sidewalk or grade level direcly below. ",
        "24. The length or height of any section of thin exterior structural-glass veneer shall not exceed ______ inches. ",
        "25. Where thin exterior structural-glass veneer is installed above the level of the top of a bulkhead or at a level more than ______ inches above the sidewalk level, the matic cement binding shall be supplemented with approved nonferrous metal shelf angles located in the horizontal joints in every course. ",
        "26. Special tests or calculations may be required for vinyl siding installed in regions where win speeds exceed ______ miles per hour. ",
        "27. Special test or calculations may be required for vinyl siding installed in regions where wind speeds exeed ______ miles per hour. ",
        "28. Nails used to fasten vinly siding shall be corrosion-resistant and shall be long enough to penetrate the studs or nailing strips by at least _____ inch",
        "29. When installing fiber cement siding on metal framing, all-weather screws shall be used and must penetrate the metal framing at least _____ full threads. ",
        "30. Weather boarding and wall covers shall be securly fastened with ____ or other approved corrosion-resistent fasteners. ",
        "31. Weather boarding and wall covers shall be securely fastened with ____ or other approved corrosion-resistent fasters. ",
        "32. Weather boarding and wall covers shall be securely fastened with ______ or other corrosion-resistent fasteners. ",
        "33. Fiber-cement siding panels shall be installed with the ______ dimemsion parallel to the framing. ",
        "34. Horizontal joints for fiber-cement siding shall be _________",
        "35. Horizontal lap siding for fiber-cement siding shall be lapped a minimum of ____ inches ",
        "36. Lap siding for fiber-cement siding shall be permitted to be instlalled with the fastner heads ______",
        "37. Where installed on exterior walls having a fire-seperation distance of ______ feet or less, combustible exterior wall coverings shall not exhibit sustained flaming. ",
        "38. The acronym MCM represents ___________",
        "39. MCM shall not be installed more than ______ feet in height above the grade plane. ",
        "40. Where the fire-seperation distance is 5 feet or less, the area of MCM shall not exceed ______ percent of the exterior-wall surface. ",
        "EXTERIOR WALLS TRUE AND FALSE",
        "1. AN EXTERIOR-WALL ENVELOPE IS A SYSTEM OR ASSEMBLY OF EXTERIOR-WALL COMPONENTS, INCLUDING FINSHED MATERIALS, THAT PROVIDES PROTECTION OF THE BUILDING STRUCTRUAL MEMBERS, INCLUDING FRAMING AND SHEATHING MATERIALS AND CONDITIONED INTERIOR SPACE, FROM THE DETRIMENTAL EFFECTS OF THE EXTERIOR ENVIRONMENT. ",
        "2. FIBER CEMENT SIDING IS A MANUFACTURED, FIBER-REINFORCING PRODUCT MADE WITH AN INORGANIC HYDRAULIC OR CALCIUM SILICATE BINDER FORMED BY CHEMICAL REACTION AND REINFORCED WITH ORGANIC OR INORGANIC NON-ABESTOS FIBERS OR BOTH. ",
        "3. METAL COMPOSITES MATERIAL IS A FACTORY-MANUFACTURED PANEL CONSISTING OF METAL SKIN BONDED TO ONE FACE OF A PLASTIC CORE. ",
        "4. VENEER IS A FACING MATERIAL USED TO INCREASE THE STRENGTH OF A WALL. ",
        "5. A SHAPED MATERIAL, MADE PRINCIPALLY FROM RIGID PLYNIYL CHLORIDE, THAT IS USED AS AN EXTERIOR WALL COVERING IS KNOWN AS VINYL SIDING. ",
        "6. WATER-RESISTIVE BARRIERS ARE INSTALLED IN FRONT OF AN EXTERIOR WALL. ",
        "7. EXTERIOR WALLS SHALL PROVIDE BUILDING WITH WEATHER-RESISTENT EVENLOPES",
        "8. AN EXTERIOR WALL ENVELOPE SHALL NOT INCLUDE FLASHING. ",
        "9. FLASHING SHALL BE INSTALLED IN SUCH A MANNER AS TO PREVENT MOISTURE FROM ENTERING A WALL OR TO REDIRECT IT TO THE EXTERIOR. ",
        "10. FALSHING SHALL NOT BE INSTALLED UNDER SILLS.",
        "11. COPING REQUIRE FLASHING THAT HAS PROJECTING FLANGES. ",
        "12. EXTERIOR-WALL POCKETS MUST BE PROTECTED FROM ACCUMULATING WATER. ",
        "13. WEEP HOLES ARE REQUIRED IN MASONRY EXTERIOR WALLS. ",
        "14. ANCHOR TIES FOR STONE VENEER MUST BE CORROSION-RESISTANT WIRE OR AN APPROVED EQUIVALENT. ",
        "15. THE LEGS OF LOOPS IN ANCHOR TIES SHALL BE NOT LESS THAT 8 INCHES IN LENGTH. ",
        "16. SLAB-TYPE VENEER UNITS NOT EXCEEDING 2 INCHES IN THICKNESS SHALL BE ANCHORED DIRECLY INTO MASONRY, CONCRETE, OR STUD CONSTRUCTION. ",
        "17. TERRA COTTA OR CERAMIC UNITS NOT LESS THAN 1 5/8 INCHES THICK SHALL BE ANCHORED DIRECLY TO MASONRY, CONCRETE, OR STUD CONSTRUCTION. ",
        "18. METAL VENEERS MUST BE, WITHOUT EXCEPTION, FABRICATED FROM APPROVED CORROSION-RESISTANT MATERIALS. ",
        "19. MASONRY BACKUP SHALL NOT BE REQUIRED FOR METAL, VENEER, EXCEPT AS IS NECESSARY TO MEET THE FIRE-RESISTANT REQUIRMENTS OF THE CODE. ",
        "20. THE AREA OF A SINGLE SECTION OF THIN EXTERIOR STRUCTURAL-GLASS VENEER SHALL NOT BE LESS THAN 0.3444 INCH. ",
        "21. THE THICKNESS OF THIN EXTERIOR STRUCTURAL-GLASS VENEER SHALL BE NOT LESS THAN 0.344 INCH. ",
        "22. THIN EXTERIOR STRUCTUAL-GLASS VENEER SHALL BE SET ONLY AFTER THE BACKING IS MOIST. ",
        "23. WHERE GLASS EXTENDS TO A SIDEWALK SURFACE, EACH SECTION SHALL REST IN AN APPROVED PLASTIC MOLDING. ",
        "24. WHEN GLASS EXTENDS TO A SIDEWALK SURFACE AND IS SET IN MOLDING, THE SPACE BETWEEN THE MOLDING AND THE SIDEWALK SHALL BE THOROUGLY CAULKED AND MADE WATERTIGHT. ",
        "25. MCM SHALL BE PERMITTED TO BE INSTALLED ON BUILDINGS OF TYPE V CONSTUCTION. ",
        "ROOF ASSEMBLIES AND ROOFTOP STRUCTURES",
        "1. A LAYER OF FELT OR NONBITMINOUS SATURATED FELT NOT LESS THEN _______ INCHES WIDE "
        
        
        
        

    ]
    let answers: [String] = [
        "International Residential Code",
        "Welfare",
        "Electrical Systems",
        "International Plumbing Code",
        "Equipment and Facilities",
        "Review Docs, Issue Notices, Grant Modifcations",
        "Filling out application",
        "Fence under 6 foot",
        "1 day",
        "Removal of structrual beams",
        "Public Service Agencies",
        "180 Days",
        "On Site",
        "Registered Design Professional",
        "Exits",
        "Reviewed For Code Compliance",
        "Deferred Documents",
        "Amended Documents",
        "Accessible",
        "Design Occupant Load, Permit #, Name/Address",
        "Occupancy",
        "The Board of Appeals",
        "Certified",
        "The building official",
        "25. Alterations",
        "True or False",
        "True",
        "False",
        "True",
        "False",
        "True",
        "True",
        "False",
        "True",
        "True",
        "False",
        "False",
        "True",
        "True",
        "False",
        "True",
        "False",
        "False",
        "False",
        "True",
        "False",
        "False",
        "False",
        "True",
        "False",
        "25. True",
        "Definitions",
        "Aerated concrete",
        "Circulation Route",
        "Combustilbe Dust",
        "100",
        "Flammable Material",
        "International Fire Code",
        "Incompatible Materials",
        "Automatic Fire Detector",
        "Tiered Seating at Stadiums",
        "Nose",
        "Anchored Masonry Veneer",
        "18",
        "Roof Recovering and Roof Replacement",
        "An opening for water drainage from the roof",
        "A qualified person approved by the building official",
        "Anchor",
        "Nominal",
        "Nominal Size",
        "Cellulosic",
        "Redwood and Eastern Cedar",
        "Srength and Utility",
        "Hardboard",
        "American National Standards Installation",
        "Single Family Dwelling",
        "Class IIIB",
        "TRUE OR FALSE",
        "True",
        "False",
        "True",
        "True",
        "False",
        "True",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "True",
        "True",
        "True",
        "False",
        "False",
        "True",
        "False",
        "False",
        "True",
        "False",
        "True:",
        "True",
        "False",
        "Hit Next",
        "Performing",
        "A3",
        "Business",
        "Combustible Liquids",
        "16",
        "Alcohol and Drug",
        "Merchandise",
        "Transient",
        "Moderate",
        "Misc and Utility",
        "100",
        "F-2",
        "International Fire Code",
        "Toxic",
        "Boarding",
        "Residential",
        "Concrete",
        "Dorms",
        "U",
        "International Residential Code",
        "50",
        "Right Clubs",
        "Jails",
        "S-2",
        "Educational",
        "HIT NEXT",
        "True",
        "True",
        "False",
        "True",
        "True",
        "False",
        "True",
        "True",
        "False",
        "False",
        "False",
        "True",
        "True",
        "False",
        "True",
        "True",
        "True",
        "False",
        "False",
        "False",
        "True",
        "True",
        "False",
        "True",
        "False",
        "HIT NEXT",
        "OLF = (.00007)(GLA) + 25",
        "30",
        "Gross Leasable Area",
        "Foyers",
        "Covered Mall Buildings",
        "Occupant Load Factor",
        "75",
        "Gross Leasable Area",
        "The Building Official",
        "A Dead End",
        "200",
        "Corridor and Exit Passageway",
        "Resistence",
        "Kiosk",
        "Anchor Stores",
        "300",
        "Vertical",
        "Standby Power and Emergency Voice/Alarm Communcations System",
        "Signs",
        "High Rise",
        "Smoke",
        "B",
        "Underground Buildings",
        "Group U",
        "2",
        "HIT NEXT",
        "False",
        "True",
        "True",
        "False",
        "False",
        "True",
        "True",
        "False",
        "False",
        "True",
        "True",
        "False",
        "False",
        "True",
        "False",
        "True",
        "True",
        "False",
        "False",
        "False",
        "True",
        "False",
        "True",
        "True",
        "True",
        "Hit Next",
        "Arabic or Alphabetical",
        "Vertical",
        "Mezzanine",
        "S",
        "Stage",
        "12",
        "Address",
        "Seperate",
        "Type II",
        "Incinerator",
        "Elevated",
        "Grade",
        "Architect",
        "7",
        "Glazed",
        "68",
        "Swimming",
        "Legible",
        "12",
        "1",
        "Click Next",
        "False",
        "False",
        "False",
        "True",
        "False",
        "True",
        "True",
        "True",
        "False",
        "True",
        "Hit Next",
        "5",
        "Glued",
        "Girders",
        "8",
        "Splice",
        "Concealed",
        "Partitions",
        "The International Mechanical and International Plumbing Codes ",
        "The ICC Electrical Code ",
        "0.5 Inches. ",
        "Click Next",
        "True",
        "True",
        "True",
        "False",
        "False",
        "True",
        "True",
        "False",
        "False",
        "True",
        "Hit Next",
        "Annular Space",
        "Fire Protection Rating",
        "Fire Blocking",
        "Walls",
        "Horizontally",
        "Parapet",
        "Type V",
        "ASTM E 119",
        "Partition",
        "I-3",
        "Interstital",
        "Louvers",
        "Self",
        "Joints",
        "Membrane",
        "T-Rating",
        "Wires",
        "Side-Hinges",
        "Labels",
        "Latch",
        "Smoke Detector",
        "Rolling",
        "25",
        "XXX",
        "International Mechanical Code",
        "Hit Next",
        "True",
        "False",
        "False",
        "True",
        "False",
        "False",
        "True",
        "False",
        "False",
        "False",
        "True",
        "False",
        "True",
        "True",
        "True",
        "False",
        "True",
        "True",
        "True",
        "False",
        "True",
        "True",
        "True",
        "False",
        "False",
        "Hit Next",
        "Be",
        "Be",
        "Flame Spread",
        "Wall Finishes, Ceiling Finishes, Floor Finishes. ",
        "Interior Floor Finishes, Carpeting, Sub Floors",
        "Picture Molds, Chair Rails. ",
        "P molds, baseboards, chair rails ",
        "Picture molds, window frames, chair rails ",
        "Door frames, handrails, chair rails. ",
        "0.25 ",
        "Hit Next",
        "False",
        "False",
        "True",
        "False",
        "True",
        "False",
        "False",
        "True",
        "True",
        "True",
        "Hit Next",
        "An approved supervising station",
        "A bell, a horn",
        "A bell, horn or light display",
        "Speaker or Text Display",
        "Circuit, condition, location",
        "Rate of temperature rise",
        "Temperature Rise and Rate of Temperature Rise",
        "Heat",
        "Clean Agent",
        "Attended or Unattended",
        "Mechanically or Chemically",
        "Flourine, Bromine, Chlorine",
        "Iodine, Chlorine",
        "2.5 Inch",
        "1.5 Inch",
        "2.5 Inch",
        "Automatic Dry Systems",
        "Automatic Wet Systmes",
        "Manual Dry Systems or Manual Wet Systems",
        "Semiautomatic Dry Systems.",
        "20,000",
        "Group A",
        "12,000",
        "300",
        "Floor",
        "A multi-theater complex",
        "5,000",
        "100",
        "Concession Stands, Retail Areas, Press Boxes",
        "20,000",
        "12,000",
        "3",
        "24,000",
        "2,500",
        "100",
        "Hazardous Exhaust",
        "Flammable materials, combustible materials, hazardous materials",
        "3",
        "Kiosks and Displays",
        "Kiosks and Booths",
        "Concession Stands and Equipment",
        "Fuel Shutoffs, Door Closers, Ventilation Systems",
        "Conveyor Openings",
        "Smoke Vents, Heat Vents, Conveyor Openings",
        "Annunication, power connections, battery calculations",
        "Ambient",
        "500",
        "Staff",
        "Manual",
        "Fire-Protection Systems True and False",
        "True",
        "True",
        "True",
        "True",
        "True",
        "False",
        "True",
        "False",
        "True",
        "False",
        "True",
        "True",
        "False",
        "False",
        "True",
        "True",
        "False",
        "True",
        "True",
        "True",
        "False",
        "True",
        "True",
        "True",
        "False",
        "False",
        "True",
        "False",
        "True",
        "True",
        "False",
        "True",
        "True",
        "True",
        "False",
        "False",
        "True",
        "True",
        "False",
        "True",
        "False",
        "False",
        "False",
        "False",
        "True",
        "True",
        "45. True",
        "Means of Egress",
        "70",
        "Bleachers",
        "Corridor",
        "A balanced door",
        "Fire exit hardware",
        "Net floor area",
        "A grandstand",
        "nosing",
        "4",
        "scissor stairs",
        "7 feet 6 inches",
        "78",
        "4",
        "12",
        "6",
        "48",
        "two-way communication",
        "50",
        "32",
        "32",
        "50",
        "50",
        "130",
        "0.75",
        "48",
        "Fences and Walls surrounding stadium",
        "44",
        "7",
        "4",
        "78",
        "Hit NEXT...YOU'RE A future GC",
        "True",
        "True",
        "True",
        "False",
        "False",
        "True",
        "True",
        "False",
        "True",
        "True",
        "True",
        "True",
        "True",
        "False",
        "False",
        "True",
        "True",
        "False",
        "True",
        "True",
        "False",
        "True",
        "True",
        "False",
        "True",
        "True",
        "False",
        "True",
        "True",
        "False",
        "Accessibility true and false",
        "Accessible",
        "An accesible route",
        "Circulation path",
        "Common Use",
        "Corridors and toilet rooms",
        "Corrdors, toilet rooms, break rooms",
        "A facility",
        "Public Use",
        "Service Entrance",
        "Goods and Services",
        "One-family and two-family",
        "Scaffolding and bridging",
        "Materials hoists and bridging",
        "Materials hoists, materails storage, construction trailers",
        "Security, life safety, observation galleries",
        "Fire towers, life safety, prison guard towers",
        "Fire towers, lifeguard stands, prisoin guard towers",
        "Crawl spaces, catwalks",
        "Freight elevators, ladders",
        "Elevator pits, elevator penthoues",
        "Mechanical rooms, elevator penthouese, electrical rooms",
        "Communications equipment rooms",
        "Restraunts, meeting rooms, churhces",
        "Piping catwalks",
        "Piping catwalks, equipment catwalks",
        "Water-treatment rooms, Sewage Treatment Rooms",
        "Water-treatment pump rooms, Sewage treatment pump rooms",
        "Electric substations, Transformer Vaults",
        "Tunnel utility facilities, highway utility facilities",
        "1",
        "Direct",
        "Tenant",
        "10",
        "20",
        "Six",
        "100",
        "24",
        "50",
        "Team or Player",
        "5",
        "5",
        "Wheelchair-accesible department",
        "Two",
        "An accessible route",
        "Detachable warning",
        "5",
        "50",
        "Are not",
        "True or False",
        "True",
        "True",
        "True",
        "True",
        "False",
        "True",
        "True",
        "False",
        "False",
        "True",
        "True",
        "False",
        "True",
        "True",
        "True",
        "True",
        "False",
        "True",
        "True",
        "False",
        "True",
        "True",
        "True",
        "True",
        "False",
        "True or Fase Interior Elements",
        "False",
        "True",
        "False",
        "True",
        "True",
        "True",
        "False",
        "True",
        "True",
        "False",
        "False",
        "True",
        "True",
        "False",
        "False",
        "True",
        "True",
        "True",
        "False",
        "True",
        "True",
        "False",
        "True",
        "False",
        "True",
        "True",
        "False",
        "True",
        "False",
        "True",
        "False",
        "True",
        "False",
        "True",
        "True",
        "False",
        "False",
        "False",
        "True",
        "True",
        "False",
        "True",
        "True",
        "False",
        "False",
        "True",
        "False",
        "True",
        "True",
        "True",
        "Exterior Walls Hit Next",
        "Adhered",
        "Anchored",
        "Backing",
        "60",
        "Joints and Seams",
        "Attachments and Seams",
        "Attachments and substrate",
        "Seams",
        "Framing and Seams",
        "Ornamentation",
        "Protection and Insulation",
        "8",
        "6.24",
        "2",
        "Flashing and Weep Holes",
        "10",
        "24",
        "20",
        "Porcelain Enamel",
        "Corrosion resistent fastenings, metal ties, approved devices. ",
        "Painting and Galvanizing",
        "10",
        "10",
        "48",
        "36",
        "100",
        "40",
        "3/4",
        "Three",
        "Copper or Zinc",
        "Zinc-Coated or Zinc",
        "Aluminum or Zinc",
        "Long",
        "Flashed with Z-flashing and blocked with solid wood framing",
        "1 1/4",
        "Dimpled",
        "10",
        "Molded Composite Materials",
        "40",
        "10",
        "TRUE AND FALSE EXTERIOR WALLS",
        "TRUE",
        "TRUE",
        "FALSE",
        "FALSE",
        "TRUE",
        "FALSE",
        "TRUE",
        "FALSE",
        "TRUE",
        "FALSE",
        "TRUE",
        "TRUE",
        "TRUE",
        "TRUE",
        "FALSE",
        "TRUE",
        "TRUE",
        "FALSE",
        "TRUE",
        "FALSE",
        "TRUE",
        "FALSE",
        "TRUE",
        "TRUE",
        
        
    ]
    var currentQuestionIndex: Int = 0
        

    
    @IBAction func showNextQuestion(_ sender: UIButton){
        currentQuestionIndex += 1
        if currentQuestionIndex == questions.count{
            currentQuestionIndex = 0
        }
        
        let question: String = questions[currentQuestionIndex]
        questionLabel.text = question
        answerLabel.text = "??"

    }
    @IBAction func showPreviousQuestion(_ sender: UIButton) {
        if currentQuestionIndex != 0{
            currentQuestionIndex -= 1
        }
        
        let question: String = questions[currentQuestionIndex]
        questionLabel.text = question
        answerLabel.text = "??"
    }
    
    @IBAction func showAnswer(_ sender: UIButton){
        let answer: String = answers[currentQuestionIndex]
        answerLabel.text = answer
        
    }
    

    override func viewDidLoad() {
        super.viewDidLoad()
        questionLabel.text = questions[currentQuestionIndex]
        // Do any additional setup after loading the view.
    }
    @IBAction func CUSTOMERSUPPORT(_ sender: Any) {guard let number = URL(string: "tel://" + "2515505660") else
    {return}
    UIApplication.shared.open(number)
    }
    

}

